# Generated by Django 4.2.2 on 2023-06-15 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='realese_type',
            field=models.CharField(choices=[(0, 'None'), (1, 'Single'), (2, 'EP'), (3, 'Album')], default=0, max_length=1, verbose_name='realese_type'),
        ),
        migrations.AddField(
            model_name='album',
            name='release_date',
            field=models.DateField(default=None, verbose_name='release_'),
        ),
    ]
