# Generated by Django 4.2.2 on 2023-06-16 06:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConcertCity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='name')),
            ],
            options={
                'verbose_name': 'concert city',
                'verbose_name_plural': 'concert citys',
            },
        ),
        migrations.CreateModel(
            name='ConcertVenue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='name')),
            ],
            options={
                'verbose_name': 'concert venue',
                'verbose_name_plural': 'concert venues',
            },
        ),
        migrations.CreateModel(
            name='Conert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=None, verbose_name='date')),
                ('ticket_status', models.PositiveBigIntegerField(choices=[(0, 'TBA'), (1, 'Free'), (2, 'In Stock'), (3, 'Sold out'), (4, 'Cancelled')], db_index=True, default=0, verbose_name='ticket status')),
                ('link', models.TextField(max_length=500, verbose_name='link')),
                ('visible', models.BooleanField(default=False, verbose_name='visible')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='concerts', to='concerts.concertcity', verbose_name='city')),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='concerts', to='concerts.concertvenue', verbose_name='venue')),
            ],
            options={
                'verbose_name': 'conert',
                'verbose_name_plural': 'conerts',
            },
        ),
    ]
