# Generated by Django 4.2.2 on 2023-06-16 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('concerts', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Conert',
            new_name='Concert',
        ),
    ]
