# Generated by Django 4.2.2 on 2023-06-20 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('concerts', '0003_alter_concert_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='concertvenue',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='concert_venues', to='concerts.concertcity', verbose_name='city'),
        ),
    ]
