# Generated by Django 4.2.2 on 2023-06-21 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('concerts', '0004_concertvenue_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='concert',
            name='city_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='city name'),
        ),
        migrations.AddField(
            model_name='concert',
            name='venue_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='venue name'),
        ),
        migrations.AlterField(
            model_name='concert',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='concerts', to='concerts.concertcity', verbose_name='city'),
        ),
        migrations.AlterField(
            model_name='concert',
            name='venue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='concerts', to='concerts.concertvenue', verbose_name='venue'),
        ),
    ]
