# Generated by Django 4.2.2 on 2023-06-20 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blogpost_picture_alter_blogpost_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='summary',
            field=models.TextField(blank=True, null=True, verbose_name='summary'),
        ),
    ]
