# Generated by Django 4.2.2 on 2023-06-19 06:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='name')),
                ('sub_category', models.CharField(max_length=20, verbose_name='sub category')),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categorys',
            },
        ),
        migrations.CreateModel(
            name='Merch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='name')),
                ('price', models.FloatField(verbose_name='price')),
                ('quantity', models.IntegerField(verbose_name='quantity')),
                ('picture', models.ImageField(upload_to='merch/', verbose_name='picture')),
                ('description', models.TextField(verbose_name='description')),
                ('album', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='merchs', to='music.album', verbose_name='album')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='merchs', to='merch.category', verbose_name='category')),
            ],
            options={
                'verbose_name': 'merch',
                'verbose_name_plural': 'merchs',
            },
        ),
    ]
